# Generated by Django 5.0.6 on 2024-06-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_expense_expense_cost_expense_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='establishment',
        ),
    ]
