# Generated by Django 5.0.6 on 2024-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expense_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='establishment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=7),
        ),
    ]
