# Generated by Django 5.0.6 on 2024-06-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_expense_establishment_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productcode',
            name='establishment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.establishment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.establishment'),
        ),
    ]
